# Generated by Django 5.2.7 on 2025-10-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
    ]
