# Generated by Django 5.2.7 on 2025-10-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
