# Generated by Django 5.2.7 on 2025-10-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
